#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml
app_cgv:
  path: /cgv/
  controller: App\Controller\ContentController::cgv
  defaults:
    title: "Conditions Générales de Vente"

app_mentionLegal:
  path: /mentionLegal/
  controller: App\Controller\ContentController::mentionLegal
  defaults:
    title: "Mentions légales"

app_politique:
  path: /politique/
  controller: App\Controller\ContentController::politique
  defaults:
    title: "Politique de confidentialité"

app_pageLogin:
  path: /pageLogin/
  controller: App\Controller\ContentController::pageLogin

app_registration:
  path: /registration/
  controller: App\Controller\ContentController::registration